package com.hendra.treasure

object MembersData {
    private val memberNames = arrayOf("Choi Hyunsuk (최현석)",
        "Park Jihoon (박지훈)",
        "Kanemoto Yoshinori (金本芳典)",
        "Kim Jun Kyu (김준규)",
        "Takata Mashiho (高田ましほ)",
        "Yoon Jae Hyuk (윤재혁)",
        "Hamada Asahi (浜田朝光)",
        "Bang Yedam (방예담)",
        "Kim Doyoung (김도영)",
        "Watanabe Haruto (渡辺春虎)",
        "Park Jeongwoo (박정우)",
        "Song Jung Hwan (소정환)")

    private val memberDetails = arrayOf("Birth Name: Choi Hyun Suk (최현석) \nEnglish Name: Daniel Choi \nPossible Position: Leader, Main Rapper, Main Dancer Birthday: April 21st, 1999 Zodiac Sign: Taurus Height: 169 cm (5’6.5″) Weight: 58 kg (128 lbs) Blood Type: A MBTI Type: ENFP Gemstone: Garnet (January Gemstone ~ 1st Member = Eldest) – Meaning Loyalty and Protection Nationality: Korean",
        "Stage Name: Jihoon (지훈) Birth Name: Park Ji Hoon (박지훈) Possible Position: Leader, Main Dancer, Lead Vocalist Birthday: March 14th, 2000 Zodiac Sign: Pisces Height: 178 cm (5’10”) Weight: 69 kg (152 lbs) Blood Type: B MBTI Type: ENTJ Gemstone: Amethyst (February Gemstone ~ 2nd Member) – Meaning Sincerity and Wisdom Nationality: Korean",
        "Stage Name: Yoshi (요시) Birth Name: Kanemoto Yoshinori (金本芳典) Korean Name: Kim Bangjeon (김방전) Possible Position: Rapper, Dancer Birthday: May 15th, 2000 Zodiac Sign: Taurus Height: 179 cm (5’10.5″) Weight: 59 kg (130 lbs) Blood Type: A MBTI Type: INFP Gemstone: Aquamarine (March Gemstone ~ 3rd Member) – Meaning Courage and Wellness Nationality: Japanese",
        "Stage Name: Junkyu (준규) Birth Name: Kim Jun Kyu (김준규) Possible Position: Vocalist, Visual Birthday: September 9th, 2000 Zodiac Sign: Virgo Height: 178 cm (5’10″) Weight: 65 kg (143 lbs) Blood Type: O MBTI Type: INFP Gemstone: Diamond (April Gemstone ~ 4th Member) – Meaning Innocence and Love Nationality: Korean",
        "Stage Name: Mashiho (마시호) Birth Name: Takata Mashiho (高田ましほ) Possible Position: Main Dancer, Vocalist, Visual Birthday: March 25th, 2001 Zodiac Sign: Aries Height: 169 cm (5’7″) Weight: 59 kg (130 lbs) Blood Type: AB MBTI Type: ENFP Gemstone: Emerald (May Gemstone ~ 5th Member) – Meaning Hope and Happiness Nationality: Japanese",
        "Stage Name: Yoon Jaehyuk (윤재혁) Birth Name: Yoon Jae Hyuk (윤재혁) Possible Position: Rapper, Vocalist Birthday: July 23rd, 2001 Zodiac Sign: Leo Height: 178 cm (5’10″) Weight: 63 kg (139 lbs) Blood Type: O MBTI Type: INFP Gemstone: Pearl (June Gemstone ~ 6th Member) – Meaning Self-Care and Emotional Healing Nationality: Korean",
        "Stage Name: Asahi (아사히) Birth Name: Hamada Asahi (浜田朝光) Possible Position: Vocalist, Visual Birthday: August 20th, 2001 Zodiac Sign: Leo Height: 172 cm (5’7.5″) Weight: 53 kg (117 lbs) Blood Type: AB MBTI Type: INFP Gemstone: Ruby (July Gemstone ~ 7th Member) – Meaning Nobility and Passion Nationality: Japanese",
        "Stage Name: Bang Yedam (방예담) Birth Name: Bang Ye Dam (방예담) Possible Position: Main Vocalist Birthday: May 7th, 2002 Zodiac Sign: Taurus Height: 172 cm (5’8″) Weight: 61 kg (134 lbs) Blood Type: A MBTI Type: INFP Gemstone: Peridot (August Gemstone ~ 8th Member) – Meaning Felicity and Creation Nationality: Korean",
        "Stage Name: Doyoung (도영) Birth Name: Kim Do Young (김도영) Possible Position: Main Dancer, Vocalist Birthday: December 4th, 2003 Zodiac Sign: Sagittarius Height: 177 cm (5’10″) Weight: 58 kg (128 lbs) Blood Type: B MBTI Type: ENTJ Gemstone: Sapphire (September Gemstone ~ 9th Member) – Meaning Calmness and Beauty of the Heart Nationality: Korean",
        "Stage Name: Haruto (하루토) Birth Name: Watanabe Haruto (渡辺春虎) Possible Position: Main Rapper, Visual Birthday: April 5th, 2004 Zodiac Sign: Aries Height: 185 cm (6’1″) Weight: 68-70kg (147-149 lbs) Blood Type: B MBTI Type: ISFP Gemstone: Opal (October Gemstone ~ 10th Member) – Meaning Focus and Inner Vision Nationality: Japanese",
        "Stage Name: Park Jeongwoo (박정우) Birth Name: Park Jeong Woo (박정우) Possible Position: Main Vocalist Birthday: September 28th, 2004 Zodiac Sign: Libra Height: 180.4 cm (5’11″) (He said he’s not sure if his height changed or not) Weight: 70 kg (154 lbs) Blood Type: O MBTI Type: ISFP Gemstone: Topaz (November Gemstone ~ 11th Member) – Meaning Friendship and Strength Nationality: Korean",
        "Stage Name: So Junghwan (소정환) Birth Name: So Jung Hwan (소정환) Possible Position: Vocalist, Dancer, Maknae Birthday: February 18, 2005 Zodiac Sign: Aquarius Height: 179.1 cm (5’10.5″) Weight: 67 kg (147 lbs) Blood Type: B MBTI Type: ENFP-T (He updated his result on March 2, 2021 via Twitter) but he said he tried hard to get an E result as most of the time his result is actually introverted (Source) Gemstone: Turquoise (December Gemstone ~ 12th Member) – Meaning Friendship and Compassion Nationality: Korean")

    private val memberFacts = arrayOf("– Hyunsuk is from Daegu, South Korea. – He has a younger brother and younger sister. – Hyunsuk trained for 5 years (as of July 2020). – His hobbies are soccer and shopping. – Hyunsuk’s favorite color is purple. (vLive) – Hyunsuk can speak a bit of English. – Hyunsuk collects lip balms. – His English name is Danny. – His inspirations are GD, Zico, Mino, Bobby, B.I, and Suga. – Hyunsuk is a former MIXNINE trainee, he ranked 5th. (He was in the debuting team, but the debut got canceled). – He doesn’t like black bean sauce ramen. – Hyunsuk passed his audition for YG through a partnership with V-Spec Academy. – His 3 phrases to describe himself is “Fashionista”, ” “Big appetite”, and “Newbie”. – He says he isn’t confident with his visuals and body proportions. – Hyunsuk knows how to compose and write songs. – He performed “Humble” in his introduction video. – Hyunsuk was the last member to be announced for Treasure.",
        "– Jihoon is from Busan, South Korea. – Has an older brother. – Jihoon trained for 4 years (as of July 2020). – He appeared in an episode of Stray Kids (JYP vs YG battle). – He used to train as Nataraja Academy. – Jihoon got the most votes as “most promising entertainment star”. – Treasure J said Jihoon speaks good Japanese. – He used to wear clear braces. – Jihoon was the 5th member to be announced for MAGNUM. – His hobby is looking at different objects and scenery like animals and paintings. – Jihoon likes to surf. – His favorite color is red. (vLive) – His English name is Jun. – His special talents is holding his breath for more than a minute and 30 seconds. – Jihoon’s favorite thing is the sky. — Jihoon is most likely to prank the other members. (Superlatives with Seventeen) – He performed “Song Goes Off” in his introduction video.",
        "– Yoshi was born in Kobe, Japan. – He is Korean-Japanese, he was born in Japan, but has an ancestry of 4th generation being Korean. He specified his nationality is Korean. (Source: Treasure Interview) – He has an older sister. – He entered taekwondo competitions under his Korean name (Kim Bangjeon). – Yoshi trained for 4 years (as of July 2020). – His hobbies are skateboarding, graffiti and watching anime. – His English name is Jaden. – Yoshinori knows how to beat box. – His favorite color is gold. (vLive) — Yoshi and Jeongwoo are the most talkative. (Superlatives with Seventeen) – His father passed away when he was in 7th grade. – His motto is “Let’s live together with music”. — Yoshi talks to himself a lot. (Superlatives with Seventeen) — Yoshi and Junghwan eat the most. (Superlatives with Seventeen) – Yoshinori likes to write songs and compose beats.",
        "– He was born in Chungju, North Chungcheong province, South Korea. – Has an older brother. – His nicknames are Koala and Handsome koala because he thinks he looks like a Koala when he smiles. – Junkyu was a child model and has been in many CF’s and photoshoots. – Junkyu attended Def Dance Skool with Doyoung. – Junkyu trained for 7 years (as of July 2020). – He has 2 cats: Ruby and Aengdu (Cherry). He addressed both of his cats as “noona”. – His favorite color is black. (vLive) – He got the most votes as “physical genius”. They said Junkyu is very tall and has broad shoulders, also his legs are long and slim. – He was a contestant on MixNine, he ranked 35th place. – His English name is David. – Junkyu’s motto is “I know the path I want to take so I’ll at it my way”. – He’s most confident in his vocals and was told that he has a voice that fits YG’s style. – Junkyu was the 4th member to announced for Treasure.",
        "– Mashiho trained for 7 years (as of July 2020). – The 3 words he’d use to describe himself are sexy, modest, and confident. – He thinks his face is cute. – Mashiho wants to become a singer that helps people have fun and enjoy themselves. – He performed “Want To Want Me” in his introduction video. – Mashiho’s hobbies are playing golf, drumming and taking pictures. – Mashiho’s motto is “Giving joy to others is the greatest gift to oneself.” – Mashiho appeared as a cafe waiter in AKMU‘s short film. – Mashiho is left-handed. — Mashiho has the most aegyo. (Superlatives with Seventeen) – His favorite color is purple. – His English name is Mama. – Mashiho has a dog named “Kotesu” in Japan. – Mashiho got voted as the most handsome by the other Treasure Box trainees. – He was the 2nd member to be announced for Magnum. – Mashiho and Keita (YG trainee) are the first YG Japan trainee (YGTB ep 2).",
        "– He was born in Yongin, Gyeonggi Province, South Korea. – He was street-cast for YG after school. – Jaehyuk is ambidextrous. (1thek originals interview – Feb 25, 2022) – He says Seokhwa is his best partner. – His English name is Kevin. – He was eliminated from the show in ep 9, but brought back for the final. – Jaehyuk has been approached by SM, JYP, CUBE, Woollim, Pledis & Yuehua. – Jaehyuk trained for almost 3 years (as of July 2020). – He trained at YG for 6 months. – He says that he’s a playful and mischievous person. – His heart flutters when he’s with someone who smells nice. – His favorite color is black. (vLive) – His charm is in his face, his left eye, and his way of walking. – He wants to be a singer because he wants to be on stage in front of many people, He wants to show them his singing and dancing skills. – Describe yourself in three words: Mischievous, King of casting, and Idol. – Jaehyuk performed “Ring Ring” by Sik-K for his introduction video – Jaehyuk was the 6th member to be announced for Treasure.",
        "– Has a younger sister and an older sister. – Asahi trained for almost 3 years (as of July 2020). – He taught himself how to self compose when he was in middle school. – His English name is Arthur. – Asahi’s hobbies are composing, soccer, and football. – Asahi can continuously kick a soccer ball, his highest record is 1000. – His favorite food are ramen and sushi. (Pops in Seoul) – He doesn’t have a favorite color, he likes all colors. (vLive) – His favorite style of clothes are vintage clothing. (Pops in Seoul) — Asahi is most likely to embarrass himself. (Superlatives with Seventeen) – Asahi performed “Lay Me Down” for his introduction video. – He was the last member to be announced for Magnum. – His three phrases are “Music is Everything”, “R&B”, and “Sweat Robot” – Asahi’s motto is “Good attitude, good mood, good music”.",
        "– Yedam is from Mapo District, Seoul, South Korea. – Yedam is an only child. – His nicknames Dami and Yedami. – Yedam trained for 7 years, almost 8 (as of July 2020). – His English name is Kyle (T-Map Ep.28). — Yedam appeared Stray Kids survival show (JYP vs YG battle). – Yedam participated in the second season of K-Pop Star. He got defeated by his labelmates, AKMU and finished as the runner up. – His father is Bang Daesik and his mother is Jeong Miyeong. – Yedam’s parents are both singers. – He can speak Korean and a bit of English. – Yedam and Sungyeon are classmates. – His favorite color is purple. (vLive) – Yedam is proved to be an amazing composer and even got credited for couple songs from Sechskies. – He composes songs with Doyoung and says that Doyoung is his best partner. – His attractive point is that he’s goofy and has a great voice. – His 3 phrases to describe himself are “17 years old”, “Searched 2000 times”, and “Magically sweet voice”. – Yedam goes to SOPA, he is under the practical music major. – He performed Pay Me Rent for his introduction video. – Yedam was the 2nd member to be announced for Treasure.",
        "– Doyoung is from Seoul, South Korea. – Has an older brother. – Doyoung trained for 5 years (as of July 2020). – His nickname is Dobi (Homebody + Doyoung). – Doyoung’s hobbies are skateboarding, swimming and playing basketball. – Doyoung says his main attraction point is his aegyo. – He performed “Lady in the Glass Dress” for his introduction video. – His 3 things to describe himself are “Bling Bling”, “Little Cutie”, and “Full of Aegyo”. – Doyoung appeared in an episode of Stray Kids (JYP vs YG battle). – Doyoung used to dance with Junkyu and Dohwan in the dance crew Def Skool. – Doyoung was voted as the 2nd most fashionista in the group. – His favorite color is yellow. (vLive) – He and Dohwan are best friends. – Doyoung is the best at cooking. (Superlatives with Seventeen) – His motto is “Challenges don’t have an end”. – Doyoung considers Yedam as his best partner. The two of them write and compose songs together. – He was the 3rd member to be announced for Magnum. – His English name is Sam (T-Map Ep.28).",
        "– Haruto is from Fukuoka, Japan. – He has a little sister. – His mom is a huge fan of BigBang and has a lot of BigBang merchandise. – His English name is Travis. – He thinks that Hyunsuk has the best visuals compared to the others, but he thinks that his visuals beat Hyunsuk’s. – He thinks his charm is that he has a handsome face, long legs, and attractive eyes. – Haruto’s 3 phrases that describe himself are “Handsome”, “Youngest rapper”, “Physical”. – He’s been called “Treasure Box’s Number 1 Visual”. – His favorite color is black. (vLive) – He really likes soda. (vLive Debut Special) – He shares a room with Junkyu. – Haruto was the first member to be announced for Treasure. – Haruto’s ideal type: someone who emphatizes with his hard work, and a kind person.",
        "– Jeongwoo is from Iksan, South Korea. – Has a brother. – Jeongwoo attends SOPA. – He is left-handed. – He has never missed a day of practice. – Jeongwoo trained for almost 3 years (as of July 2020). — Jeongwoo and Yoshi are the most talkative. (Superlatives with Seventeen) – Jeongwoo likes listening to music, clothes, and food. — Jeongwoo has the best fashion sense. (Superlatives with Seventeen) – His strong point is that he can make his voice sound really powerful. – His favorite color is turquoise. (vLive) – Three expressions that describe him are “Great reactions”, “Great singer”, and “tanned skin”. – Jeongwoo and Junghwan came form the same dance academy in Iksan. – He performed When I Was You Man in his introduction video. – Jeongwoo was the 5th member to be announced for Treasure. – His English name is Justin (T-Map Ep.28).",
        "– Junghwan trained for almost 3 years (as of July 2020). – Junghwan was in K tigers and is really good at acrobatics. – Junghwan says Inhong is his best friend. – His nickname is sloth (Junkyu gave him his nickname). – His English name is John. – Junghwan was a child model and appeared in many CF’s. – If Junghwan is a girl, he will fall for Yedam because his voice will melt him. [SURVEY CAM] – Three things describing himself are “sparkling eyes”, “Persistent”, and “attractive side”. – Junghwan’s motto is “Don’t make efforts go in vain.” – His specialties are Taekwondo and dancing. – His favorite color is pink. (vLive) – His attraction points that his sharp jawline and hooked nose are attractive. – Junghwan and Jeongwoo came form the same dance academy in Iksan. – He performed Supermarket Flowers in his introduction video. – Junghwan was the 3rd member to be announced for Treasure. – Has the same birthday as J-Hope (BTS), DK (SEVENTEEN), and Vernon (SEVENTEEN).")

    private val membersImages = intArrayOf(R.drawable.choi_hyunsuk,
        R.drawable.park_jihoon,
        R.drawable.yoshi,
        R.drawable.kim_junkyu,
        R.drawable.mashiho,
        R.drawable.yoon_jaehyuk,
        R.drawable.asahi,
        R.drawable.bang_yedam,
        R.drawable.kim_doyoung,
        R.drawable.haruto,
        R.drawable.park_jeongwoo,
        R.drawable.song_junghwan)

    val listData: ArrayList<Member>
        get() {
            val list = arrayListOf<Member>()
            for (position in memberNames.indices) {
                val member = Member()
                member.name = memberNames[position]
                member.detail = memberDetails[position]
                member.facts = memberFacts[position]
                member.photo = membersImages[position]
                list.add(member)
            }
            return list
        }
}