package com.hendra.treasure

object MembersData {
    private val memberNames = arrayOf("Choi Hyun Suk (최현석)",
        "Park Ji Hoon (박지훈)",
        "Kanemoto Yoshinori (金本芳典)",
        "Kim Jun Kyu (김준규)",
        "Takata Mashiho (高田ましほ)",
        "Yoon Jae Hyuk (윤재혁)",
        "Hamada Asahi (浜田朝光)",
        "Bang Ye Dam (방예담)",
        "Kim Do Young (김도영)",
        "Watanabe Haruto (渡辺春虎)",
        "Park Jeong Woo (박정우)",
        "Song Jung Hwan (소정환)")

    private val memberDetails = arrayOf("Birth Name: Choi Hyun Suk (최현석) \nEnglish Name: Daniel Choi \nPossible Position: Leader, Main Rapper, Main Dancer \nBirthday: April 21st, 1999 \nZodiac Sign: Taurus \nHeight: 169 cm (5’6.5″) \nWeight: 58 kg (128 lbs) \nBlood Type: A \nMBTI Type: ENFP \nNationality: Korean",
        "Stage Name: Jihoon (지훈) \nBirth Name: Park Ji Hoon (박지훈) \nPossible Position: Leader, Main Dancer, Lead Vocalist \nBirthday: March 14th, 2000 \nZodiac Sign: Pisces \nHeight: 178 cm (5’10”) \nWeight: 69 kg (152 lbs) \nBlood Type: B \nMBTI Type: ENTJ \nNationality: Korean",
        "Stage Name: Yoshi (요시) \nBirth Name: Kanemoto Yoshinori (金本芳典) \nKorean Name: Kim Bangjeon (김방전) \nPossible Position: Rapper, Dancer \nBirthday: May 15th, 2000 \nZodiac Sign: Taurus \nHeight: 179 cm (5’10.5″) \nWeight: 59 kg (130 lbs) \nBlood Type: A \nMBTI Type: INFP \nNationality: Japanese",
        "Stage Name: Junkyu (준규) \nBirth Name: Kim Jun Kyu (김준규) \nPossible Position: Vocalist, Visual \nBirthday: September 9th, 2000 \nZodiac Sign: Virgo \nHeight: 178 cm (5’10″) \nWeight: 65 kg (143 lbs) \nBlood Type: O \nMBTI Type: INFP \nNationality: Korean",
        "Stage Name: Mashiho (마시호) \nBirth Name: Takata Mashiho (高田ましほ) \nPossible Position: Main Dancer, Vocalist, Visual \nBirthday: March 25th, 2001 \nZodiac Sign: Aries \nHeight: 169 cm (5’7″) \nWeight: 59 kg (130 lbs) \nBlood Type: AB \nMBTI Type: ENFP \nNationality: Japanese",
        "Stage Name: Yoon Jaehyuk (윤재혁) \nBirth Name: Yoon Jae Hyuk (윤재혁) \nPossible Position: Rapper, Vocalist \nBirthday: July 23rd, 2001 \nZodiac Sign: Leo \nHeight: 178 cm (5’10″) \nWeight: 63 kg (139 lbs) \nBlood Type: O \nMBTI Type: INFP \nNationality: Korean",
        "Stage Name: Asahi (아사히) \nBirth Name: Hamada Asahi (浜田朝光) \nPossible Position: Vocalist, Visual \nBirthday: August 20th, 2001 \nZodiac Sign: Leo \nHeight: 172 cm (5’7.5″) \nWeight: 53 kg (117 lbs) \nBlood Type: AB \nMBTI Type: INFP \nNationality: Japanese",
        "Stage Name: Bang Yedam (방예담) \nBirth Name: Bang Ye Dam (방예담) \nPossible Position: Main Vocalist \nBirthday: May 7th, 2002 \nZodiac Sign: Taurus \nHeight: 172 cm (5’8″) \nWeight: 61 kg (134 lbs) \nBlood Type: A \nMBTI Type: INFP \nNationality: Korean",
        "Stage Name: Doyoung (도영) \nBirth Name: Kim Do Young (김도영) \nPossible Position: Main Dancer, Vocalist \nBirthday: December 4th, 2003 \nZodiac Sign: Sagittarius \nHeight: 177 cm (5’10″) \nWeight: 58 kg (128 lbs) \nBlood Type: B \nMBTI Type: ENTJ \nNationality: Korean",
        "Stage Name: Haruto (하루토) \nBirth Name: Watanabe Haruto (渡辺春虎) \nPossible Position: Main Rapper, Visual \nBirthday: April 5th, 2004 \nZodiac Sign: Aries \nHeight: 185 cm (6’1″) \nWeight: 68-70kg (147-149 lbs) \nBlood Type: B \nMBTI Type: ISFP \nNationality: Japanese",
        "Stage Name: Park Jeongwoo (박정우) \nBirth Name: Park Jeong Woo (박정우) \nPossible Position: Main Vocalist \nBirthday: September 28th, 2004 \nZodiac Sign: Libra \nHeight: 180.4 cm (5’11″) (He said he’s not sure if his height changed or not) \nWeight: 70 kg (154 lbs) \nBlood Type: O MBTI \nType: ISFP \nNationality: Korean",
        "Stage Name: So Junghwan (소정환) \nBirth Name: So Jung Hwan (소정환) \nPossible Position: Vocalist, Dancer, Maknae \nBirthday: February 18, 2005 \nZodiac Sign: Aquarius \nHeight: 179.1 cm (5’10.5″) \nWeight: 67 kg (147 lbs) \nBlood Type: B \nMBTI Type: ENFP-T (He updated his result on March 2, 2021 via Twitter) but he said he tried hard to get an E result as most of the time his result is actually introverted (Source) \nNationality: Korean")

    private val memberFacts = arrayOf("– Hyunsuk is from Daegu, South Korea. \n– He has a younger brother and younger sister. \n– Hyunsuk trained for 5 years (as of July 2020). \n– His hobbies are soccer and shopping. \n– Hyunsuk’s favorite color is purple. (vLive) \n– Hyunsuk can speak a bit of English. \n– Hyunsuk collects lip balms. \n– His English name is Danny. \n– His inspirations are GD, Zico, Mino, Bobby, B.I, and Suga. \n– Hyunsuk is a former MIXNINE trainee, he ranked 5th. (He was in the debuting team, but the debut got canceled). \n– He doesn’t like black bean sauce ramen. \n– Hyunsuk passed his audition for YG through a partnership with V-Spec Academy. \n– His 3 phrases to describe himself is “Fashionista”, ” “Big appetite”, and “Newbie”. \n– He says he isn’t confident with his visuals and body proportions. \n– Hyunsuk knows how to compose and write songs. \n– He performed “Humble” in his introduction video. \n– Hyunsuk was the last member to be announced for Treasure.",
        "– Jihoon is from Busan, South Korea. \n– Has an older brother. \n– Jihoon trained for 4 years (as of July 2020). \n– He appeared in an episode of Stray Kids (JYP vs YG battle). \n– He used to train as Nataraja Academy. \n– Jihoon got the most votes as “most promising entertainment star”. \n– Treasure J said Jihoon speaks good Japanese. \n– He used to wear clear braces. \n– Jihoon was the 5th member to be announced for MAGNUM. \n– His hobby is looking at different objects and scenery like animals and paintings. \n– Jihoon likes to surf. – His favorite color is red. (vLive) \n– His English name is Jun. \n– His special talents is holding his breath for more than a minute and 30 seconds. \n– Jihoon’s favorite thing is the sky. \n— Jihoon is most likely to prank the other members. (Superlatives with Seventeen) \n– He performed “Song Goes Off” in his introduction video.",
        "– Yoshi was born in Kobe, Japan. \n– He is Korean-Japanese, he was born in Japan, but has an ancestry of 4th generation being Korean. \n- He specified his nationality is Korean. (Source: Treasure Interview) \n– He has an older sister. \n– He entered taekwondo competitions under his Korean name (Kim Bangjeon). \n– Yoshi trained for 4 years (as of July 2020). \n– His hobbies are skateboarding, graffiti and watching anime. \n– His English name is Jaden. \n– Yoshinori knows how to beat box. – His favorite color is gold. (vLive) \n— Yoshi and Jeongwoo are the most talkative. (Superlatives with Seventeen) \n– His father passed away when he was in 7th grade. \n– His motto is “Let’s live together with music”. \n— Yoshi talks to himself a lot. (Superlatives with Seventeen) \n— Yoshi and Junghwan eat the most. (Superlatives with Seventeen) \n– Yoshinori likes to write songs and compose beats.",
        "– He was born in Chungju, North Chungcheong province, South Korea. \n– Has an older brother. \n– His nicknames are Koala and Handsome koala because he thinks he looks like a Koala when he smiles. \n– Junkyu was a child model and has been in many CF’s and photoshoots. \n– Junkyu attended Def Dance Skool with Doyoung. \n– Junkyu trained for 7 years (as of July 2020). \n– He has 2 cats: Ruby and Aengdu (Cherry). He addressed both of his cats as “noona”. \n– His favorite color is black. (vLive) – He got the most votes as “physical genius”. They said Junkyu is very tall and has broad shoulders, also his legs are long and slim. \n– He was a contestant on MixNine, he ranked 35th place. \n– His English name is David. \n– Junkyu’s motto is “I know the path I want to take so I’ll at it my way”. \n– He’s most confident in his vocals and was told that he has a voice that fits YG’s style. \n– Junkyu was the 4th member to announced for Treasure.",
        "– Mashiho trained for 7 years (as of July 2020). \n– The 3 words he’d use to describe himself are sexy, modest, and confident. \n– He thinks his face is cute. \n– Mashiho wants to become a singer that helps people have fun and enjoy themselves. \n– He performed “Want To Want Me” in his introduction video. \n– Mashiho’s hobbies are playing golf, drumming and taking pictures. \n– Mashiho’s motto is “Giving joy to others is the greatest gift to oneself.” \n– Mashiho appeared as a cafe waiter in AKMU‘s short film. \n– Mashiho is left-handed. \n— Mashiho has the most aegyo. (Superlatives with Seventeen) \n– His favorite color is purple. \n– His English name is Mama. \n– Mashiho has a dog named “Kotesu” in Japan. \n– Mashiho got voted as the most handsome by the other Treasure Box trainees. \n– He was the 2nd member to be announced for Magnum. \n– Mashiho and Keita (YG trainee) are the first YG Japan trainee (YGTB ep 2).",
        "– He was born in Yongin, Gyeonggi Province, South Korea. \n– He was street-cast for YG after school. \n– Jaehyuk is ambidextrous. (1thek originals interview – Feb 25, 2022) \n– He says Seokhwa is his best partner. \n– His English name is Kevin. \n– He was eliminated from the show in ep 9, but brought back for the final. \n– Jaehyuk has been approached by SM, JYP, CUBE, Woollim, Pledis & Yuehua. \n– Jaehyuk trained for almost 3 years (as of July 2020). \n– He trained at YG for 6 months. – He says that he’s a playful and mischievous person. \n– His heart flutters when he’s with someone who smells nice. \n– His favorite color is black. (vLive) \n– His charm is in his face, his left eye, and his way of walking. \n– He wants to be a singer because he wants to be on stage in front of many people, He wants to show them his singing and dancing skills. \n– Describe yourself in three words: Mischievous, King of casting, and Idol. \n– Jaehyuk performed “Ring Ring” by Sik-K for his introduction video \n– Jaehyuk was the 6th member to be announced for Treasure.",
        "– Has a younger sister and an older sister. \n– Asahi trained for almost 3 years (as of July 2020). \n– He taught himself how to self compose when he was in middle school. \n– His English name is Arthur. \n– Asahi’s hobbies are composing, soccer, and football. \n– Asahi can continuously kick a soccer ball, his highest record is 1000. \n– His favorite food are ramen and sushi. (Pops in Seoul) \n– He doesn’t have a favorite color, he likes all colors. (vLive) \n– His favorite style of clothes are vintage clothing. (Pops in Seoul) \n— Asahi is most likely to embarrass himself. (Superlatives with Seventeen) \n– Asahi performed “Lay Me Down” for his introduction video. \n– He was the last member to be announced for Magnum. \n– His three phrases are “Music is Everything”, “R&B”, and “Sweat Robot” \n– Asahi’s motto is “Good attitude, good mood, good music”.",
        "– Yedam is from Mapo District, Seoul, South Korea. \n– Yedam is an only child. \n– His nicknames Dami and Yedami. \n– Yedam trained for 7 years, almost 8 (as of July 2020). \n– His English name is Kyle (T-Map Ep.28). \n— Yedam appeared Stray Kids survival show (JYP vs YG battle). \n– Yedam participated in the second season of K-Pop Star. He got defeated by his labelmates, AKMU and finished as the runner up. \n– His father is Bang Daesik and his mother is Jeong Miyeong. \n– Yedam’s parents are both singers. \n– He can speak Korean and a bit of English. \n– Yedam and Sungyeon are classmates. \n– His favorite color is purple. (vLive) \n– Yedam is proved to be an amazing composer and even got credited for couple songs from Sechskies. \n– He composes songs with Doyoung and says that Doyoung is his best partner. \n– His attractive point is that he’s goofy and has a great voice. \n– His 3 phrases to describe himself are “17 years old”, “Searched 2000 times”, and “Magically sweet voice”. \n– Yedam goes to SOPA, he is under the practical music major. \n– He performed Pay Me Rent for his introduction video. \n– Yedam was the 2nd member to be announced for Treasure.",
        "– Doyoung is from Seoul, South Korea. \n– Has an older brother. \n– Doyoung trained for 5 years (as of July 2020). \n– His nickname is Dobi (Homebody + Doyoung). \n– Doyoung’s hobbies are skateboarding, swimming and playing basketball. \n– Doyoung says his main attraction point is his aegyo. \n– He performed “Lady in the Glass Dress” for his introduction video. \n– His 3 things to describe himself are “Bling Bling”, “Little Cutie”, and “Full of Aegyo”. \n– Doyoung appeared in an episode of Stray Kids (JYP vs YG battle). –\n Doyoung used to dance with Junkyu and Dohwan in the dance crew Def Skool. \n– Doyoung was voted as the 2nd most fashionista in the group. \n– His favorite color is yellow. (vLive) \n– He and Dohwan are best friends. \n– Doyoung is the best at cooking. (Superlatives with Seventeen) \n– His motto is “Challenges don’t have an end”. \n– Doyoung considers Yedam as his best partner. The two of them write and compose songs together. \n– He was the 3rd member to be announced for Magnum. \n– His English name is Sam (T-Map Ep.28).",
        "– Haruto is from Fukuoka, Japan. \n– He has a little sister. \n– His mom is a huge fan of BigBang and has a lot of BigBang merchandise. \n– His English name is Travis. \n– He thinks that Hyunsuk has the best visuals compared to the others, but he thinks that his visuals beat Hyunsuk’s. \n– He thinks his charm is that he has a handsome face, long legs, and attractive eyes. \n– Haruto’s 3 phrases that describe himself are “Handsome”, “Youngest rapper”, “Physical”. \n– He’s been called “Treasure Box’s Number 1 Visual”. \n– His favorite color is black. (vLive) \n– He really likes soda. (vLive Debut Special) \n– He shares a room with Junkyu. \n– Haruto was the first member to be announced for Treasure. \n– Haruto’s ideal type: someone who emphatizes with his hard work, and a kind person.",
        "– Jeongwoo is from Iksan, South Korea. \n– Has a brother. \n– Jeongwoo attends SOPA. \n– He is left-handed. \n– He has never missed a day of practice. \n– Jeongwoo trained for almost 3 years (as of July 2020). \n— Jeongwoo and Yoshi are the most talkative. (Superlatives with Seventeen) \n– Jeongwoo likes listening to music, clothes, and food. \n— Jeongwoo has the best fashion sense. (Superlatives with Seventeen) \n– His strong point is that he can make his voice sound really powerful. \n– His favorite color is turquoise. (vLive) \n– Three expressions that describe him are “Great reactions”, “Great singer”, and “tanned skin”. –\n Jeongwoo and Junghwan came form the same dance academy in Iksan. \n– He performed When I Was You Man in his introduction video. \n– Jeongwoo was the 5th member to be announced for Treasure. \n– His English name is Justin (T-Map Ep.28).",
        "– Junghwan trained for almost 3 years (as of July 2020). \n– Junghwan was in K tigers and is really good at acrobatics. \n– Junghwan says Inhong is his best friend. \n– His nickname is sloth (Junkyu gave him his nickname). \n– His English name is John. \n– Junghwan was a child model and appeared in many CF’s. \n– If Junghwan is a girl, he will fall for Yedam because his voice will melt him. [SURVEY CAM] \n– Three things describing himself are “sparkling eyes”, “Persistent”, and “attractive side”. \n– Junghwan’s motto is “Don’t make efforts go in vain.” \n– His specialties are Taekwondo and dancing. \n– His favorite color is pink. (vLive) \n– His attraction points that his sharp jawline and hooked nose are attractive. \n– Junghwan and Jeongwoo came form the same dance academy in Iksan. \n– He performed Supermarket Flowers in his introduction video. \n– Junghwan was the 3rd member to be announced for Treasure. \n– Has the same birthday as J-Hope (BTS), DK (SEVENTEEN), and Vernon (SEVENTEEN).")

    private val membersImages = intArrayOf(R.drawable.choi_hyunsuk,
        R.drawable.park_jihoon,
        R.drawable.yoshi,
        R.drawable.kim_junkyu,
        R.drawable.mashiho,
        R.drawable.yoon_jaehyuk,
        R.drawable.asahi,
        R.drawable.bang_yedam,
        R.drawable.kim_doyoung,
        R.drawable.haruto,
        R.drawable.park_jeongwoo,
        R.drawable.song_junghwan)

    val listData: ArrayList<Member>
        get() {
            val list = arrayListOf<Member>()
            for (position in memberNames.indices) {
                val member = Member()
                member.name = memberNames[position]
                member.detail = memberDetails[position]
                member.facts = memberFacts[position]
                member.photo = membersImages[position]
                list.add(member)
            }
            return list
        }
}